title: Your Title
author:
  email: "YourEmail@example.com"
  name: Your Name
description: >- # this means to ignore newlines until "baseurl:"
  Description for the website
baseurl: "" # the subpath of your site, e.g. /blog
url: https://template.ealexander.ca # the base hostname & protocol for your site, e.g. http://example.com
domain: template.ealexander.ca
# enable or disable this if you want the description to show up below posts in the post list
show_description: true
# Build settings
remote_theme: jekyll/minima
google_analytics: 
header_pages:
  - index.markdown
  - resume/index.markdown
  - transcript.markdown
#removed until filled in  - about.markdown
  - linkedin.markdown
plugins:
  - jekyll-remote-include
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-redirect-from
logo: /assets/icons/logo.svg
minima:
  skin: auto
  # socisl links automatically get shown at the bottom and a script creates auto redirects from the platform and from tag "https://example.com/git
  social_links:
    - { platform: github,  user_url: "github.com", from: "git"}
    - { platform: youtube, user_url: "youtube.com", from: "yt" }
    - { platform: linkedin, user_url: "linkedin.com", from: "li" }
    - { platform: strava, user_url: "strava.com", from: "st" }
    - { platform: facebook, user_url: "facebook.com", from: "fb" }
    - { platform: twitter, user_url: "twitter.com", from: "tw" }
defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path:            "resume/**/*.pdf"
    values:
      sitemap: false
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
